name: foodly
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  entry: ^0.0.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  rename: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo_foreground.png
  adaptive_icon_background: "#ffffff"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images


  fonts: 
    - family: mulish
      fonts: 
        - asset: assets\fonts\mulish\Mulish-Regular.ttf
          weight: 500

    - family: mulishMedium
      fonts: 
        - asset: assets\fonts\mulish\Mulish-Medium.ttf
          weight: 600

    - family: mulishBold
      fonts: 
        - asset: assets\fonts\mulish\Mulish-Bold.ttf
          weight: 700

    - family: mPlusMedium
      fonts: 
        - asset: assets\fonts\mPlusRounded\MPLUSRounded1c-Medium.ttf
          weight: 600

    - family: mPlusBold
      fonts: 
        - asset: assets\fonts\mPlusRounded\MPLUSRounded1c-Bold.ttf
          weight: 700

    - family: comfortaa
      fonts: 
        - asset: assets\fonts\comfortaa\Comfortaa-Bold.ttf
          weight: 600

    

    
